### ISSUE TITLE
Clean up system install: use JSON, remove direction names, remove file upload fallback

### ISSUE THREAD

**Issue by lauramroa** [jamespfennell/transiter#33]
- Send a JSON payload instead. TOML is nice, but kind of funky to be sending in a HTTP request.
- Don't install direction names through this endpoint. Instead come up with a new endpoint, or remove the feature entirely.
- Remove file upload fallback feature. If required, a user can disable the required_for_install flag and then perform a manual update (ability to be implemented)

**Comment by jamespfennell** [comment]
Resolved as part of the YAML migration
